export const Config = {
    CANVAS_SIZE: 1000,
    BINARY_TREE_WIDTH: 300,
    BINARY_TREE_ROW_HEIGHT: 30,
    BINARY_TREE_BRANCH_COLOR: "#FFFFFF",
    HIGHLIGHT_COLOR: "#97dcff47",
    HIGHLIGHT_BORDER: "#97dcff",
    NODE_HIGHLIGHT_COLOR: "#81fbff",
    DEFAULT_COLOR: "#FFFFFF"
} as const;